# Modified by smalvy, 2026 — adapted for portfolio-project-2
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-project-2

  Sample SAM Template for portfolio-project-2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  VersionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: version_function/
      Handler: app.version_handler
      Runtime: python3.14
      Architectures:
        - x86_64

Outputs:
  VersionFunction:
    Description: "Version Lambda Function ARN"
    Value: !GetAtt VersionFunction.Arn
  VersionFunctionIamRole:
    Description: "Implicit IAM Role created for Version function"
    Value: !GetAtt VersionFunctionRole.Arn
